pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'smart-erp'
include 'erp-backend'
include 'erp-mobile-app:app'
project(':erp-mobile-app:app').projectDir = new File('erp-mobile-app/app')
