[settings]
; 🚀 모든 리얼타임 기능을 정지하여 파일 시스템과의 충돌을 방지합니다.
; ps_endpoints => odbc,asterisk
; ps_auths => odbc,asterisk
; ps_aors => odbc,asterisk
; ps_contacts => odbc,asterisk
; ps_transports => odbc,asterisk
; extensions => odbc,asterisk
; queues => odbc,asterisk
; queue_members => odbc,asterisk
