[general]
static=yes
writeprotect=no

[from-internal]
; 💡 DB에서 from-internal에 해당하는 시나리오 로드
switch => Realtime/@extensions

[ivr-main]
; 💡 DB에서 ivr-main에 해당하는 시나리오 로드
switch => Realtime/@extensions

[after-hours]
; 💡 DB에서 after-hours에 해당하는 시나리오 로드
switch => Realtime/@extensions
