[general]
static=yes
writeprotect=no

[from-internal]
switch => Realtime/from-internal@extensions

[ivr-main]
switch => Realtime/ivr-main@extensions

[after-hours]
switch => Realtime/after-hours@extensions
