[modules]
autoload = yes
load = res_odbc.so
load = res_config_odbc.so
load = pbx_realtime.so
load = func_realtime.so
load = res_pjsip.so
load = res_pjsip_registrar.so
load = res_pjsip_authenticator_digest.so
noload = chan_sip.so
