[modules]
autoload=yes

; 💡 리얼타임 핵심 모듈
load => res_odbc.so
load => res_config_odbc.so

; 💡 PJSIP 핵심 모듈
load => res_pjsip.so
load => res_pjsip_session.so
load => chan_pjsip.so

; 💡 대기열 및 어플리케이션 모듈 (이게 핵심)
load => app_queue.so
load => res_musiconhold.so
load => app_dial.so
load => app_mixmonitor.so
load => app_playback.so

; 💡 불필요한 모듈 로드 방지
noload => chan_sip.so
