[modules]
autoload = yes

; 🚀 [CTI 및 대기열 필수 부품]
load = res_rtp_asterisk.so
load = chan_sip.so
load = app_queue.so
load = res_manager.so

load = codec_ulaw.so
load = codec_alaw.so
load = format_wav.so
load = format_pcm.so
load = format_sln.so

; ❌ [차단]
noload = res_pjsip_rfc4733.so
noload = chan_pjsip.so
noload = res_config_odbc.so
noload = res_sorcery_realtime.so
noload = pbx_realtime.so
