[asterisk-connector]
Description = MySQL connection to Asterisk DB
; 🚀 드라이버 이름을 직접 경로로 지정하여 인식률을 높임
Driver      = /usr/lib/x86_64-linux-gnu/odbc/libmyodbc8w.so
Database    = asterisk
Server      = asterisk-db
User        = root
Password    = Crmbank123!
Port        = 3306
Option      = 3
Charset     = utf8mb4
