[global]
type=global
user_agent=Smart-ERP-PBX

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; --- 101번 ---
[101]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=auth101
aors=aor101
dtmf_mode=info

[auth101]
type=auth
auth_type=userpass
password=101password
username=101

[aor101]
type=aor
max_contacts=5

; --- 103번 ---
[103]
type=endpoint
context=from-internal
disallow=all
allow=ulaw,alaw
auth=auth103
aors=aor103
dtmf_mode=info

[auth103]
type=auth
auth_type=userpass
password=103password
username=103

[aor103]
type=aor
max_contacts=5
