[general]
persistentmembers = yes
autofill = yes
monitor-type = MixMonitor
eventwhencalled = yes
eventmemberstatus = yes
ringinuse = no

[sales_group]
musicclass = default
strategy = ringall
timeout = 20
retry = 5
wrapuptime = 0
joinempty = yes
leavewhenempty = no
member => SIP/101,0,이정우님
member => SIP/102,0,영업상담원102

[support_group]
strategy = linear
timeout = 15
member => SIP/121,0,지원상담원121
member => SIP/122,0,지원상담원122

[management_group]
strategy = ringall
timeout = 20
member => SIP/131,0,경영상담원131
member => SIP/132,0,경영상담원132
