server {
    listen 80;
    server_name localhost;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://172.18.0.7:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/crm/inbound/play-recording {
        proxy_pass http://172.18.0.7:8080/api/crm/inbound/play-recording;
        proxy_hide_header Content-Type;
        add_header Content-Type audio/wav;
    }
}
