# spring.config.import=file:/data/erp/config/env-prod.properties
spring.application.name=${SPRING_APPLICATION_NAME:smart-erp}
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api
resource.prefix=
spring.mvc.async.request-timeout=7200s

######### session ############
spring.session.timeout=PT10H

# spring session
spring.session.store-type=none
spring.cache.type=none
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,\
org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

######### session ############
logging.level.root=INFO
logging.level.org.mybatis=DEBUG
logging.level.com.crmbank.erp=DEBUG

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.from=${MAIL_SMTP_FROM}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS:true}
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ehlo=false

logging.level.org.springframework.mail=DEBUG

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}
spring.jackson.time-zone=Asia/Seoul
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# Asterisk Settings
asterisk.host=${ASTERISK_HOST}
asterisk.port=${ASTERISK_PORT:5038}
asterisk.username=${ASTERISK_USERNAME:admin}
asterisk.password=${ASTERISK_PASSWORD:gkdldhs12#$}

######### Google Gemini AI Settings ############
google.ai.gemini.api-key=${GEMINI_API_KEY:AIzaSyCDvUwDSjNpqesOpFVEXzC7EH910Dg3ptk}
google.ai.gemini.model-name=gemini-1.5-pro

######### Chatwoot SSO Settings ############
chatwoot.api.url=${CHATWOOT_URL:http://localhost:3000}
chatwoot.account.id=${CHATWOOT_ACCOUNT_ID:1}
chatwoot.inbox.id=${CHATWOOT_INBOX_ID:1}
chatwoot.access.token=${CHATWOOT_ACCESS_TOKEN:FvDEbYNM16jAJGY9hZQ1ymvY}

logging.level.org.asteriskjava.manager.internal.ResponseBuilderImpl=ERROR
logging.level.org.asteriskjava.manager.internal.EventBuilderImpl=ERROR
